import pandas as pd
import glob
import os
import re
import shutil

def analyze_latest_run():
    # 1. Find the most recent CSV file generated by the bot
    # Search both the LiveTrader subfolder and project root (published exe writes to root)
    csv_files = (glob.glob("PredictionLiveTrader/LivePaperTrades_*.csv")
               + glob.glob("LivePaperTrades_*.csv")
               + glob.glob("PredictionLiveTrader/bin/Release/**/LivePaperTrades_*.csv", recursive=True))

    # Filter out our snapshot file so we don't accidentally analyze an old snapshot
    valid_files = [f for f in csv_files if "SNAPSHOT" not in f and "_summary" not in f]

    if valid_files:
        latest_file = max(valid_files, key=os.path.getctime)
        # 2. THE SAFE CLONE: Copy the live file to a snapshot at project root
        snapshot_file = "LivePaperTrades_SNAPSHOT.csv"
        try:
            shutil.copy2(latest_file, snapshot_file)
            print(f"\n📸 Created safe snapshot: {os.path.basename(latest_file)}")
        except Exception as e:
            print(f"Failed to create snapshot: {e}")
            return
    else:
        # Fallback: use existing snapshot files directly
        snapshot_candidates = glob.glob("LivePaperTrades_SNAPSHOT*.csv") + [f for f in csv_files if "SNAPSHOT" in f and "_summary" not in f]
        if not snapshot_candidates:
            print("No CSV files found! Make sure the bot has exported a ledger.")
            return
        snapshot_file = max(snapshot_candidates, key=os.path.getctime)
        latest_file = snapshot_file
        print(f"\n📸 No live CSV found — using existing snapshot: {os.path.basename(snapshot_file)}")

    print("="*80)
    print(f"📊 ANALYZING SNAPSHOT DATA")
    print("="*80)

    # 3. Load the data from the SNAPSHOT, not the live file
    df = pd.read_csv(snapshot_file)

    if df.empty:
        print("CSV is empty — no trades to analyze yet.")
        return

    # Convert Timestamp to actual DateTime objects for time-based analysis
    df['Timestamp'] = pd.to_datetime(df['Timestamp'])

    # 4. Handle all trade sides correctly
    buy_sides = {'BUY', 'BUY NO'}
    df['CashFlow'] = df.apply(
        lambda row: -row['DollarValue'] if row['Side'] in buy_sides else row['DollarValue'],
        axis=1
    )

    # Load reject counts from summary CSV if it exists
    summary_file = latest_file.replace(".csv", "_summary.csv")
    snapshot_summary = snapshot_file.replace(".csv", "_summary.csv")
    reject_counts = {}
    if os.path.exists(summary_file):
        try:
            shutil.copy2(summary_file, snapshot_summary)
            summary_df = pd.read_csv(snapshot_summary)
            reject_counts = dict(zip(summary_df['StrategyName'], summary_df['RejectedOrders']))
        except Exception:
            pass

    # Extract starting capital per strategy from CSV (falls back to $1000 for old CSVs)
    if 'StartingCapital' in df.columns:
        starting_caps = df.drop_duplicates('StrategyName').set_index('StrategyName')['StartingCapital'].to_dict()
    else:
        starting_caps = {}

    # Extract strategy type and parameters
    df['StrategyType'] = df['StrategyName'].apply(lambda x: x.split('_v')[0].split('_Ultra')[0])

    def extract_params(name):
        params = re.findall(r'_([A-Z]+)([0-9.]+)', name)
        return {k: float(v) for k, v in params}

    df['Params'] = df['StrategyName'].apply(extract_params)

    # ==========================================
    # DASHBOARD 1: STRATEGY LEADERBOARD
    # ==========================================

    sell_sides = {'SELL', 'SELL NO', 'RESOLVE YES', 'RESOLVE NO'}
    leaderboard = df.groupby('StrategyName').agg(
        Total_PnL=('CashFlow', 'sum'),
        Buys=('Side', lambda x: x.isin(buy_sides).sum()),
        Sells=('Side', lambda x: x.isin(sell_sides).sum()),
    ).reset_index()
    leaderboard['Rejects'] = leaderboard['StrategyName'].map(reject_counts).fillna(0).astype(int)

    # --- True Win/Loss tracking via round-trip trades ---
    # A "round trip" starts with a BUY and ends when all shares are sold/resolved.
    # If the bot buys the same market again, that's a new round trip.
    # PnL is the sum of cashflows (buy is negative, sell is positive).
    round_trip_stats = {}
    for strat, strat_df in df.sort_values('Timestamp').groupby('StrategyName'):
        wins = 0
        losses = 0
        open_trips = 0  # round trips still open (no exit yet)
        for asset, asset_df in strat_df.groupby('AssetId'):
            trip_pnl = 0.0
            in_trip = False
            for _, row in asset_df.iterrows():
                if row['Side'] in buy_sides:
                    if in_trip:
                        # New buy while already in a trip — close the old one first
                        if trip_pnl >= 0:
                            wins += 1
                        else:
                            losses += 1
                    # Start a new round trip
                    in_trip = True
                    trip_pnl = row['CashFlow']  # negative (cost of entry)
                elif row['Side'] in sell_sides:
                    trip_pnl += row['CashFlow']  # positive (proceeds)
            # After all trades for this asset: check if trip was closed
            if in_trip:
                # Check if position is fully closed (net shares ~ 0)
                yes_held = asset_df[asset_df['Side'] == 'BUY']['Shares'].sum() - asset_df[asset_df['Side'].isin(['SELL', 'RESOLVE YES'])]['Shares'].sum()
                no_held = asset_df[asset_df['Side'] == 'BUY NO']['Shares'].sum() - asset_df[asset_df['Side'].isin(['SELL NO', 'RESOLVE NO'])]['Shares'].sum()
                if abs(yes_held) < 0.01 and abs(no_held) < 0.01:
                    # Position fully closed — score the round trip
                    if trip_pnl >= 0:
                        wins += 1
                    else:
                        losses += 1
                else:
                    open_trips += 1
        round_trip_stats[strat] = {'Wins': wins, 'Losses': losses, 'Open': open_trips}

    rt_df = pd.DataFrame(round_trip_stats).T.reset_index().rename(columns={'index': 'StrategyName'})
    leaderboard = leaderboard.merge(rt_df, on='StrategyName', how='left')
    leaderboard[['Wins', 'Losses', 'Open']] = leaderboard[['Wins', 'Losses', 'Open']].fillna(0).astype(int)

    # --- Mark-to-Market calculations (merged into leaderboard) ---
    last_prices = df.sort_values('Timestamp').groupby('AssetId')['ExecutionPrice'].last().to_dict()

    df['Yes_Share_Change'] = df.apply(lambda r: r['Shares'] if r['Side'] == 'BUY' else (-r['Shares'] if r['Side'] in ('SELL', 'RESOLVE YES') else 0), axis=1)
    df['No_Share_Change'] = df.apply(lambda r: r['Shares'] if r['Side'] == 'BUY NO' else (-r['Shares'] if r['Side'] in ('SELL NO', 'RESOLVE NO') else 0), axis=1)

    inventory = df.groupby('StrategyName').agg(
        Net_Yes_Shares=('Yes_Share_Change', 'sum'),
        Net_No_Shares=('No_Share_Change', 'sum')
    ).reset_index()

    LIQUIDITY_HAIRCUT = 0.07
    inventory['MarkToMarket_Value'] = 0.0

    for idx, row in inventory.iterrows():
        strat = row['StrategyName']
        strat_trades = df[df['StrategyName'] == strat]
        open_assets = strat_trades['AssetId'].unique()
        strat_mtm = 0.0
        for asset in open_assets:
            asset_trades = strat_trades[strat_trades['AssetId'] == asset]
            yes_held = asset_trades[asset_trades['Side'] == 'BUY']['Shares'].sum() - asset_trades[asset_trades['Side'].isin(['SELL', 'RESOLVE YES'])]['Shares'].sum()
            no_held = asset_trades[asset_trades['Side'] == 'BUY NO']['Shares'].sum() - asset_trades[asset_trades['Side'].isin(['SELL NO', 'RESOLVE NO'])]['Shares'].sum()
            last_price = last_prices.get(asset, 0)
            if yes_held > 0:
                strat_mtm += (yes_held * last_price)
            if no_held > 0:
                strat_mtm += (no_held * (1 - last_price))
        inventory.at[idx, 'MarkToMarket_Value'] = strat_mtm * (1 - LIQUIDITY_HAIRCUT)

    # Merge inventory into leaderboard
    leaderboard = leaderboard.merge(inventory[['StrategyName', 'MarkToMarket_Value']], on='StrategyName', how='left')
    leaderboard['MarkToMarket_Value'] = leaderboard['MarkToMarket_Value'].fillna(0.0)

    leaderboard['StartingCapital'] = leaderboard['StrategyName'].map(starting_caps).fillna(1000.0)
    leaderboard['True_Total_Equity'] = leaderboard['StartingCapital'] + leaderboard['Total_PnL'] + leaderboard['MarkToMarket_Value']
    leaderboard['True_PnL'] = leaderboard['True_Total_Equity'] - leaderboard['StartingCapital']
    leaderboard['Worst_Case_Equity'] = leaderboard['StartingCapital'] + leaderboard['Total_PnL']
    leaderboard['Worst_Case_PnL'] = leaderboard['Worst_Case_Equity'] - leaderboard['StartingCapital']

    strat_time_span = df.groupby('StrategyName')['Timestamp'].agg(['min', 'max'])
    strat_time_span['Hours'] = (strat_time_span['max'] - strat_time_span['min']).dt.total_seconds() / 3600.0
    strat_time_span['Hours'] = strat_time_span['Hours'].clip(lower=0.1)
    leaderboard = leaderboard.merge(strat_time_span[['Hours']], left_on='StrategyName', right_index=True, how='left')
    leaderboard['Hourly_PnL'] = leaderboard['True_PnL'] / leaderboard['Hours']

    # Sort and format
    leaderboard = leaderboard.sort_values('True_Total_Equity', ascending=False)
    leaderboard['Total_PnL_fmt'] = leaderboard['Total_PnL'].apply(lambda x: f"${x:,.2f}")
    closed_trips = leaderboard['Wins'] + leaderboard['Losses']
    total_trips = closed_trips + leaderboard['Open']
    leaderboard['WinRate%'] = (leaderboard['Wins'] / closed_trips.replace(0, 1) * 100).apply(lambda x: f"{x:.0f}%")
    leaderboard['Closure%'] = (closed_trips / total_trips.replace(0, 1) * 100).apply(lambda x: f"{x:.0f}%")
    leaderboard['W/L'] = leaderboard.apply(lambda r: f"{r['Wins']}W/{r['Losses']}L/{r['Open']}O", axis=1)
    leaderboard['Cash_Left'] = leaderboard['Worst_Case_Equity'].apply(lambda x: f"${x:,.2f}")
    leaderboard['MTM_Value'] = leaderboard['MarkToMarket_Value'].apply(lambda x: f"${x:,.2f}")
    leaderboard['Equity'] = leaderboard['True_Total_Equity'].apply(lambda x: f"${x:,.2f}")
    leaderboard['True_PnL_fmt'] = leaderboard['True_PnL'].apply(lambda x: f"${x:,.2f}")
    leaderboard['Worst_PnL'] = leaderboard['Worst_Case_PnL'].apply(lambda x: f"${x:,.2f}")
    leaderboard['Hours_fmt'] = leaderboard['Hours'].apply(lambda x: f"{x:.1f}h")
    leaderboard['PnL_hr'] = leaderboard['Hourly_PnL'].apply(lambda x: f"${x:,.2f}/hr")

    print("\n🏆 STRATEGY LEADERBOARD (Sorted by Equity)")
    print("-" * 120)
    print(leaderboard[['StrategyName', 'Equity', 'True_PnL_fmt', 'PnL_hr', 'Cash_Left', 'MTM_Value', 'Worst_PnL', 'W/L', 'WinRate%', 'Closure%', 'Rejects', 'Hours_fmt']].to_string(index=False))

    # ==========================================
    # DASHBOARD 2: PARAMETER IMPACT ANALYSIS
    # ==========================================
    print("\n🔬 PARAMETER IMPACT (Which settings work best?)")
    print("-" * 80)

    all_params = df['Params'].apply(pd.Series).stack().reset_index(level=1)
    all_params.columns = ['Param', 'Value']
    all_params['CashFlow'] = df.loc[all_params.index, 'CashFlow']
    all_params['StrategyName'] = df.loc[all_params.index, 'StrategyName']

    strategy_pnl = df.groupby('StrategyName')['CashFlow'].sum().reset_index()
    strategy_pnl.columns = ['StrategyName', 'StrategyPnL']

    param_names = {'T': 'Threshold', 'W': 'Window', 'P': 'TakeProfit', 'S': 'StopLoss', 'ES': 'EntrySlippage', 'XS': 'ExitSlippage'}

    for param_letter in sorted(df['Params'].apply(lambda d: list(d.keys())).explode().dropna().unique()):
        param_label = param_names.get(param_letter, param_letter)
        param_vals = df.drop_duplicates('StrategyName')[['StrategyName', 'Params']].copy()
        param_vals['ParamValue'] = param_vals['Params'].apply(lambda d: d.get(param_letter))
        param_vals = param_vals.dropna(subset=['ParamValue'])

        if param_vals.empty:
            continue

        param_vals = param_vals.merge(strategy_pnl, on='StrategyName')
        summary = param_vals.groupby('ParamValue').agg(
            Avg_PnL=('StrategyPnL', 'mean'),
            Strategies=('StrategyName', 'count')
        ).reset_index()

        summary = summary.sort_values('Avg_PnL', ascending=False)
        summary['Avg_PnL'] = summary['Avg_PnL'].apply(lambda x: f"${x:,.2f}")

        print(f"  [{param_label}] (param '{param_letter}')")
        print(summary.to_string(index=False))
        print()

    # ==========================================
    # DASHBOARD 3: HOURLY REGIME ANALYSIS
    # ==========================================
    print("⏰ HOURLY REGIME ANALYSIS (Top 5 Winners & Losers per Hour)")
    print("-" * 120)

    df['Hour'] = df['Timestamp'].dt.floor('h')
    hourly_strat = df.groupby(['Hour', 'StrategyName'])['CashFlow'].sum().reset_index()

    for hour in sorted(hourly_strat['Hour'].unique()):
        hour_data = hourly_strat[hourly_strat['Hour'] == hour].sort_values('CashFlow', ascending=False)
        hour_total = hour_data['CashFlow'].sum()
        top5 = hour_data.head(5)
        bot5 = hour_data.tail(5).sort_values('CashFlow', ascending=True)

        print(f"\n  [{pd.Timestamp(hour).strftime('%Y-%m-%d %H:%M')}] Net: ${hour_total:,.2f}")
        for _, r in top5.iterrows():
            print(f"    + {r['StrategyName']:<50} ${r['CashFlow']:>10,.2f}")
        for _, r in bot5.iterrows():
            print(f"    - {r['StrategyName']:<50} ${r['CashFlow']:>10,.2f}")

    # Export full strategy x hour matrix to CSV
    hourly_pivot = hourly_strat.pivot_table(index='Hour', columns='StrategyName', values='CashFlow', fill_value=0)
    hourly_pivot['NET_TOTAL'] = hourly_pivot.sum(axis=1)
    hourly_export = "PredictionLiveTrader/Hourly_Strategy_Breakdown.csv"
    hourly_pivot.to_csv(hourly_export)
    print(f"\n  💾 Full hourly breakdown exported to '{hourly_export}'")
    print()


if __name__ == "__main__":
    analyze_latest_run()