import pandas as pd
import glob
import os

def analyze_latest_run():
    # 1. Find the most recent CSV file generated by the bot
    # Update the path if your CSVs are saving in a different folder!
    csv_files = glob.glob("PredictionLiveTrader/LivePaperTrades_*.csv") 
    
    if not csv_files:
        print("No CSV files found! Make sure the bot has exported a ledger.")
        return

    latest_file = max(csv_files, key=os.path.getctime)
    print(f"\n📊 ANALYZING LATEST RUN: {os.path.basename(latest_file)}\n")
    print("="*60)

    # 2. Load the data
    df = pd.read_csv(latest_file)

    # 3. Create the 'CashFlow' column (Buys cost money, Sells make money)
    df['CashFlow'] = df.apply(lambda row: -row['DollarValue'] if row['Side'] == 'BUY' else row['DollarValue'], axis=1)

    # ==========================================
    # DASHBOARD 1: STRATEGY LEADERBOARD
    # ==========================================
    print("🏆 STRATEGY LEADERBOARD (Sorted by Profit)")
    print("-" * 60)
    
    # Group by Strategy, sum the CashFlow, and count total executions
    leaderboard = df.groupby('StrategyName').agg(
        Total_PnL=('CashFlow', 'sum'),
        Executions=('Side', 'count')
    ).reset_index()
    
    # Sort from most profitable to least
    leaderboard = leaderboard.sort_values('Total_PnL', ascending=False)
    
    # Format the PnL as currency
    leaderboard['Total_PnL'] = leaderboard['Total_PnL'].apply(lambda x: f"${x:,.2f}")
    print(leaderboard.to_string(index=False))
    print("\n")

    # ==========================================
    # DASHBOARD 2: BUY / SELL WIN RATE CHECK
    # ==========================================
    print("⚖️  EXECUTION BALANCE (Are bots holding bags?)")
    print("-" * 60)
    
    # Pivot the data to show counts of BUYs vs SELLs
    breakdown = df.groupby(['StrategyName', 'Side']).size().unstack(fill_value=0).reset_index()
    print(breakdown.to_string(index=False))
    print("\n")

    # ==========================================
    # DASHBOARD 3: MARKET BREAKDOWN
    # ==========================================
    print("🌍 TOP 5 TRADED MARKETS (By Volume/Activity)")
    print("-" * 60)
    
    # Group by Market to see where the bots are spending the most time
    markets = df.groupby('MarketName').agg(
        Net_PnL=('CashFlow', 'sum'),
        Executions=('Side', 'count')
    ).reset_index().sort_values('Executions', ascending=False).head(5)

    markets['Net_PnL'] = markets['Net_PnL'].apply(lambda x: f"${x:,.2f}")
    
    # Truncate long market names so it fits nicely in the console
    markets['MarketName'] = markets['MarketName'].apply(lambda x: x[:45] + "..." if len(x) > 45 else x)
    print(markets.to_string(index=False))
    print("\n" + "="*60 + "\n")

if __name__ == "__main__":
    analyze_latest_run()