import pandas as pd
import glob
import os
import re

def analyze_latest_run():
    # 1. Find the most recent CSV file generated by the bot
    csv_files = glob.glob("PredictionLiveTrader/LivePaperTrades_*.csv")

    if not csv_files:
        print("No CSV files found! Make sure the bot has exported a ledger.")
        return

    latest_file = max(csv_files, key=os.path.getctime)
    print(f"\n📊 ANALYZING LATEST RUN: {os.path.basename(latest_file)}\n")
    print("="*70)

    # 2. Load the data
    df = pd.read_csv(latest_file)

    if df.empty:
        print("CSV is empty — no trades to analyze yet.")
        return

    # 3. FIX: Handle all trade sides correctly
    # Sides from the broker: BUY, SELL, BUY NO, SELL NO, RESOLVE YES, RESOLVE NO
    buy_sides = {'BUY', 'BUY NO'}
    df['CashFlow'] = df.apply(
        lambda row: -row['DollarValue'] if row['Side'] in buy_sides else row['DollarValue'],
        axis=1
    )

    # 4. Extract strategy type and parameters from names like "Sniper_v3_T0.15_W20"
    df['StrategyType'] = df['StrategyName'].apply(lambda x: x.split('_v')[0].split('_Ultra')[0])

    # Extract all parameter key-value pairs (e.g., T0.15, W20, P0.10)
    def extract_params(name):
        params = re.findall(r'_([A-Z])([0-9.]+)', name)
        return {k: float(v) for k, v in params}

    df['Params'] = df['StrategyName'].apply(extract_params)

    # ==========================================
    # DASHBOARD 1: STRATEGY LEADERBOARD
    # ==========================================
    print("🏆 STRATEGY LEADERBOARD (Sorted by Profit)")
    print("-" * 70)

    leaderboard = df.groupby('StrategyName').agg(
        Total_PnL=('CashFlow', 'sum'),
        Buys=('Side', lambda x: x.isin(buy_sides).sum()),
        Sells=('Side', lambda x: (~x.isin(buy_sides)).sum()),
    ).reset_index()

    leaderboard = leaderboard.sort_values('Total_PnL', ascending=False)
    leaderboard['Total_PnL_fmt'] = leaderboard['Total_PnL'].apply(lambda x: f"${x:,.2f}")

    print(leaderboard[['StrategyName', 'Total_PnL_fmt', 'Buys', 'Sells']].to_string(index=False))
    print("\n")

    # ==========================================
    # DASHBOARD 2: PARAMETER IMPACT ANALYSIS
    # ==========================================
    print("🔬 PARAMETER IMPACT (Which settings work best?)")
    print("-" * 70)

    # For each parameter letter (T=Threshold, W=Window, P=TakeProfit),
    # show average PnL across all strategies that use that value
    all_params = df['Params'].apply(pd.Series).stack().reset_index(level=1)
    all_params.columns = ['Param', 'Value']
    all_params['CashFlow'] = df.loc[all_params.index, 'CashFlow']
    all_params['StrategyName'] = df.loc[all_params.index, 'StrategyName']

    # Get PnL per strategy first, then average by parameter value
    strategy_pnl = df.groupby('StrategyName')['CashFlow'].sum().reset_index()
    strategy_pnl.columns = ['StrategyName', 'StrategyPnL']

    # For each unique parameter, show how different values perform
    param_names = {'T': 'Threshold', 'W': 'Window', 'P': 'TakeProfit'}

    for param_letter in sorted(df['Params'].apply(lambda d: list(d.keys())).explode().dropna().unique()):
        param_label = param_names.get(param_letter, param_letter)

        # Extract this param value per strategy
        param_vals = df.drop_duplicates('StrategyName')[['StrategyName', 'Params']].copy()
        param_vals['ParamValue'] = param_vals['Params'].apply(lambda d: d.get(param_letter))
        param_vals = param_vals.dropna(subset=['ParamValue'])

        if param_vals.empty:
            continue

        param_vals = param_vals.merge(strategy_pnl, on='StrategyName')

        summary = param_vals.groupby('ParamValue').agg(
            Avg_PnL=('StrategyPnL', 'mean'),
            Strategies=('StrategyName', 'count')
        ).reset_index()

        summary = summary.sort_values('Avg_PnL', ascending=False)
        summary['Avg_PnL'] = summary['Avg_PnL'].apply(lambda x: f"${x:,.2f}")

        print(f"  [{param_label}] (param '{param_letter}')")
        print(summary.to_string(index=False))
        print()

    # ==========================================
    # DASHBOARD 3: STRATEGY TYPE COMPARISON
    # ==========================================
    print("📊 STRATEGY TYPE COMPARISON (Sniper vs RevArb vs ...)")
    print("-" * 70)

    type_summary = df.groupby('StrategyType').agg(
        Total_PnL=('CashFlow', 'sum'),
        Strategies=('StrategyName', 'nunique'),
        Executions=('Side', 'count')
    ).reset_index().sort_values('Total_PnL', ascending=False)

    type_summary['Avg_PnL_Per_Strategy'] = (type_summary['Total_PnL'] / type_summary['Strategies']).apply(lambda x: f"${x:,.2f}")
    type_summary['Total_PnL'] = type_summary['Total_PnL'].apply(lambda x: f"${x:,.2f}")

    print(type_summary.to_string(index=False))
    print("\n")

    # ==========================================
    # DASHBOARD 4: EXECUTION BALANCE
    # ==========================================
    print("⚖️  EXECUTION BALANCE (Are bots holding bags?)")
    print("-" * 70)

    breakdown = df.groupby(['StrategyName', 'Side']).size().unstack(fill_value=0).reset_index()
    print(breakdown.to_string(index=False))
    print("\n")

    # ==========================================
    # DASHBOARD 5: TOP TRADED MARKETS
    # ==========================================
    print("🌍 TOP 10 TRADED MARKETS (By Activity)")
    print("-" * 70)

    markets = df.groupby('MarketName').agg(
        Net_PnL=('CashFlow', 'sum'),
        Executions=('Side', 'count'),
        Strategies=('StrategyName', 'nunique')
    ).reset_index().sort_values('Executions', ascending=False).head(10)

    markets['Net_PnL'] = markets['Net_PnL'].apply(lambda x: f"${x:,.2f}")
    markets['MarketName'] = markets['MarketName'].apply(lambda x: x[:50] + "..." if len(x) > 50 else x)
    print(markets.to_string(index=False))
    print("\n" + "="*70 + "\n")

if __name__ == "__main__":
    analyze_latest_run()
