// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PredictionBacktester.Data.Database;

#nullable disable

namespace PredictionBacktester.Data.Migrations
{
    [DbContext(typeof(PolymarketDbContext))]
    [Migration("20260216164502_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("PredictionBacktester.Core.Entities.Database.Market", b =>
                {
                    b.Property<string>("MarketId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MarketId");

                    b.ToTable("Markets");
                });

            modelBuilder.Entity("PredictionBacktester.Core.Entities.Database.Outcome", b =>
                {
                    b.Property<string>("OutcomeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OutcomeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("OutcomeId");

                    b.HasIndex("MarketId");

                    b.ToTable("Outcomes");
                });

            modelBuilder.Entity("PredictionBacktester.Core.Entities.Database.Trade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("OutcomeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProxyWallet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Size")
                        .HasColumnType("TEXT");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TransactionHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProxyWallet");

                    b.HasIndex("OutcomeId", "Timestamp");

                    b.ToTable("Trades");
                });

            modelBuilder.Entity("PredictionBacktester.Core.Entities.Database.Outcome", b =>
                {
                    b.HasOne("PredictionBacktester.Core.Entities.Database.Market", "Market")
                        .WithMany("Outcomes")
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Market");
                });

            modelBuilder.Entity("PredictionBacktester.Core.Entities.Database.Market", b =>
                {
                    b.Navigation("Outcomes");
                });
#pragma warning restore 612, 618
        }
    }
}
